#!/bin/bash
user="$1"
type="$2"
uniq /root/usuarios.db > /tmp/checkdb
database="/root/usuarios.db"

user_exist() {
    if [[ "$(grep -wc "$user" /etc/passwd)" != '0' ]]; then
        echo "$user"
    else
        echo 'Not exist'
    fi
}

cont_online() {
    limit="$(grep -w "$user" "$database" | cut -d' ' -f2)"
    conssh="$(ps -u "$user" | grep sshd | wc -l)"
    if [[ -z $limit ]]; then limit="1"; fi
    if [[ $conssh -gt $limit ]]; then screen -dmS pkill pkill.sh "$user"; fi
    echo "$conssh"
}

limiter_user() {
    limit="$(grep -w "$user" "$database" | cut -d' ' -f2)"
    if [[ -z $limit ]]; then limit="1"; fi
    echo "$limit"
}

check_data() {
    datauser=$(chage -l "$user" | grep -i co | awk -F : '{print $2}')
    dat="$(date -d"$datauser" '+%d/%m/%Y')"
    echo "$dat"
}

check_dias() {
    datauser=$(chage -l "$user" | grep -i co | awk -F : '{print $2}')
    dat="$(date -d"$datauser" '+%Y-%m-%d')"
    data=$(echo -e "$((($(date -ud "$dat" +%s) - $(date -ud "$(date +%Y-%m-%d)" +%s)) / 86400))")
    echo "$data"
}

check_new_data() {
    if [[ "$(grep -wc "$user" /etc/passwd)" != '0' ]]; then
        datauser=$(chage -l "$user" | grep -i co | awk -F : '{print $2}')
        dat="$(date -d"$datauser" '+%Y%m%d')"
        echo "$dat"
    else
        echo 'Not exist'
    fi
}

datacheck_new() {
    if [[ "$(grep -wc "$user" /etc/passwd)" != '0' ]]; then
        datauser=$(chage -l "$user" | grep -i co | awk -F : '{print $2}')
        dat="$(date -d"$datauser" '+%d%m%Y')"
        echo "$dat"
    else
        echo 'Not exist'
    fi
}

case $type in
    1) user_exist ;;
    2) cont_online ;;
    3) limiter_user ;;
    4) check_data ;;
    5) check_dias ;;
    6) check_new_data ;;
    7) datacheck_new ;;
    *) echo "Invalid option" ;;
esac
